[package]
name = "combine"
description = "combine files"
version = "0.1.0"
edition = "2024"

[features]
tracing = ["dep:tracing"]
progress = ["dep:indicatif"]
cli = ["tracing", "dep:clap"]

[dependencies]
crossbeam-channel = "0.5.17"
tracing = { version = "0.1.44", optional = true }
indicatif = { version = "0.18.6", optional = true }
clap = { version = "4.6.7", optional = true, features = ["derive"] }

[[bin]]
name = "combine"
path = "src/bin/cli.rs"
required-features = ["cli"]
